name: Clojure CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CLJ_PATH: /home/runner/clojure
  ACTIONS_STEP_DEBUG: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache clj deps
        id: cache-clj-deps
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-build-clj-deps-${{ hashFiles('deps.edn', 'build.clj', '.github/workflows/clojure.yml') }}
      - name: install clojure
        run: |
          curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
          chmod +x linux-install.sh
          sudo ./linux-install.sh --prefix ${CLJ_PATH}
          echo "${CLJ_PATH}/bin" >> $GITHUB_PATH
      - name: execute tests
        run: clojure -M:test
      - name: build uberjar
        run: clojure -T:build uber
      - name: archive uberjar
        uses: actions/upload-artifact@v3
        with:
          name: findjar-standalone-jar
          path: |
            target/findjar-*-standalone.jar
            gen-resources/build/version.edn
            LICENSE

